#!/usr/bin/env python2.7

import os
import sys

import nflgame.game
import nflgame.schedule
import nflvid

for eid in sorted(nflgame.schedule.games_byid):
    info = nflgame.schedule.games_byid[eid]
    g = nflgame.game.Game(info['eid'])
    nice = '(%s, %s)' % (g.eid, g.gamekey)

    if g.schedule['season_type'] != 'REG':
        # Only regular season for now.
        continue
    if g.season() <= 2009:
        # 2010 and earlier has really spotty coverage at this URL.
        continue
    if os.access('nflvid/pbp-xml/%s-%s.xml.gz' % (g.eid, g.gamekey), os.R_OK):
        continue

    print >> sys.stderr, 'Downloading for %s' % nice
    ps = nflvid.plays(g)  # Saves the XML to disk automatically.
    if ps is None:
        print >> sys.stderr, 'Could not download XML for game %s' % nice
